### ISSUE TITLE
Create empty project model

### ISSUE THREAD

**Issue by Cheesely** [ImanKahlila/CodeCollab#11]
Build the schema Models for users and projects.

**Comment by ThomasCarney315** [comment]
@Cheesely, If you are done with the issue 11 branch, you can delete it as a best practice to keep everything a little cleaner. 

The easiest way to delete a branch is to click on the little branch icon/button and then click the trashcan on the branch


![Image](https://github.com/ImanKahlila/ProjectHunt/assets/118192650/4804a867-e0fb-40ea-9362-10094a6ddbc4)

**Comment by Cheesely** [comment]
Thanks for the reminder @ThomasCarney315! Just deleted it.
