### ISSUE TITLE
Create starting point / Frame or structure the project

### ISSUE THREAD

**Issue by jeramief** [ImanKahlila/CodeCollab#6]

**Comment by IntelliJinceTech** [comment]
If practicing agile, use of scrum framework with sprint plannings, retros, etc. ? Or use Kanban to track tickets? 

Or we use more of an open-source approach?

**Comment by jeramief** [comment]
I believe we're going for more of a scrum approach without the sprints.

**Comment by jeramief** [comment]
Started MVC template frame.
